name: demo
description: "A new Flutter project."
publish_to: 'none'

version: 5.4.2+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  bot_toast: ^4.1.3
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.0
  bloc: ^8.1.0
  equatable: ^2.0.0
  flutter_bloc: ^8.1.1
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  retrofit: ^4.2.0
  intl: ^0.18.0
  intl_translation: ^0.20.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  uuid: ^4.4.0
  html_unescape: ^2.0.0
  html: ^0.15.4
  crypto: ^3.0.3
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  card_swiper: ^3.0.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  fading_edge_scrollview: ^4.1.1
  auto_size_text: ^3.0.0
  chewie: ^1.8.3
  pinyin: ^3.3.0
  sqflite: ^2.3.3+1
  video_player: ^2.9.1
  flutter_floating: ^1.0.7
  date_format: ^2.0.7
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0
  scrollable_positioned_list: ^0.3.8
  visibility_detector: ^0.4.0+2
  flutter_widget_from_html_core: ^0.15.1
  flutter_slidable: ^3.1.1
  sliver_tools: ^0.2.12
  fl_chart: ^0.68.0
  skeletonizer: ^1.4.2
  connectivity_plus: ^6.0.5
  collection: ^1.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.1
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.1
  flutter_gen_runner:





flutter:
  uses-material-design: true
  assets:
    - assets/activity/
    - assets/common/


flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_native_splash:
  background_image: assets/config/launch_page_bg.webp
  android: true
  ios: true
